### ISSUE TITLE
No Contect-Type

### ISSUE THREAD

**Issue by amrza** [gebi/go-fileupload-example#1]
this code cant upload files correctly, because it does not define headers for Content-Type and boundary info. not all servers can handle this kind of request.
its an easy fix by `writer.FormDataContentType()`, but im not sure how to pass its values to `Header.Add()`. i tried to use channels but i keep getting `fatal error: all goroutines are asleep - deadlock!`

**Comment by nimolix** [comment]
@amirr3za You can easily create a custom boundary (randomBoundary function in multipart package) and send it as a argument to the streamingUploadFile function and set a "Content-Type" header accordingly. 

``` go
func streamingUploadFile(params map[string]string, paramName, path, boundary string, w *io.PipeWriter, file *os.File) {
    defer file.Close()
    defer w.Close()
    writer := multipart.NewWriter(w)
    writer.SetBoundary(boundry)
    part, err := writer.CreateFormFile(paramName, filepath.Base(path))
    if err != nil {
        log.Fatal(err)
        return
    }
    _, err = io.Copy(part, file)
    if err != nil {
        log.Fatal(err)
        return
    }

    for key, val := range params {
        _ = writer.WriteField(key, val)
    }

    err = writer.Close()
    if err != nil {
        log.Fatal(err)
        return
    }
}

// Creates a new file upload http request with optional extra params
func newfileUploadRequest(uri string, params map[string]string, paramName, path string) (*http.Request, error) {
    file, err := os.Open(path)
    if err != nil {
        return nil, err
    }

    r, w := io.Pipe()
    boundry := RandomBoundry
    go streamingUploadFile(params, paramName, path, boundary, w, file)
    request, err := http.NewRequest("POST", uri, r)
    if err != nil {
        return nil, err
    }
    request.Header.Set("Content-Type", "multipart/form-data; boundary="+boundary)
    return request, err
}

func RandomBoundary() string {
    var buf [30]byte
    _, err := io.ReadFull(rand.Reader, buf[:])
    if err != nil {
        panic(err)
    }
    return fmt.Sprintf("%x", buf[:])
}
```

**Comment by amrza** [comment]
@nimolix Wow, I had forgotten that i wrote this here, its an old issue. I managed to do multipart uploads. the real problem was not Go; i had not a clear understanding of how multipart requests works in HTTP. I always worked on the other side of the story (upload handlers). However, mamnoon baraye vaghti ke gozashti, blog shoma oon ghadima az avalin blog hayee bood ke man dar zamineye barnamenevisi mikhoonadam :)
